### ISSUE TITLE
ipa書き込み時のパスが間違っている

### ISSUE THREAD

**Issue by subdiox** [BlitzModder/BMPC#40]
`World of Tanks 3.9.0.ipa/Data`に書き込まれてるけど、
`World of Tanks 3.9.0.ipa/Payload/wotblitz.app/Data`が正しい

**Comment by S--Minecraft** [comment]
適用端末iOSになってる？

**Comment by subdiox** [comment]
あ、Macになってたすまん

**Comment by S--Minecraft** [comment]
#26 で確認入れようと思ったけど結局実装してない()
