### ISSUE TITLE
リポジトリの形式

### ISSUE THREAD

**Issue by S--Minecraft** [BlitzModder/BMPC#5]
BMのリポジトリ、次の決まりで読み込むように統一したい

/が0個かつhttp:から始まらない→githubのmasterブランチのURLに「(入力内容)/BMRepository」を当てはめる
/が1個かつhttp:から始まらない→githubのmasterブランチのURLに「(入力内容)」を当てはめる
/が2個以上かつhttp:から始まる→URLをそのまま使う
それ以外→「リポジトリの形式が違います」というエラーを出す

githubに関しては、masterブランチ以外無視する

たとえば、リポジトリ入力画面で「BlitzModder」を入力した場合は、https://github.com/BlitzModder/BMRepository/raw/master/
をリポジトリのURLとして読み込むってこと

https://BlitzModder.github.io/BMRepository/
でもいいよ

**Comment by subdiox** [comment]
Prefixの判定文字列を"http:"じゃなくて「"http://"もしくは"https://"」に変更して欲しい

**Comment by S--Minecraft** [comment]
対応済みよ
